### ISSUE TITLE
[Suggestion] Ability to view deleted inventory from creative mode

### ISSUE THREAD

**Issue by Mark1ed** [glisco03/deathlog#29]
When I was playing in the survival world and switched to creative I accidentally clicked clear inventory and lost all the stuff, that's why I lost the world :( .Hope you will add such feature :/

**Comment by gliscowo** [comment]
While I understand that this can be frustrating issue, I don't think it is something that DeathLog should help with. The goal of this mod is strictly to have a log of when and how you've died over the course of your playthrough and to provide a means of recovery in case of unfair, bugged or otherwise non-sensical deaths.

DeathLog, however, is not and will not be a general-purpose backup solution - there are other mods out there which do this and do it much better than DeathLog ever will

Cheers
