### ISSUE TITLE
1.20.6 and 1.21

### ISSUE THREAD

**Issue by itsarian** [glisco03/deathlog#41]
any plans to update to 1.20.6 and 1.21?

**Comment by gliscowo** [comment]
Rest assured that a 1.21 port is underway and nearing completion, but due to the large number of changes in Minecraft (and a moderate amount of tech debt I'm currently repaying with a substantial refactoring) it might take a few more days to be finished. 

I'm afraid I won't be providing a 1.20.5/6 version, seeing how little usage the version is and most likely will be seeing.

Cheers

**Comment by matgaw123** [comment]
This mod is so cool can I somehow suport you guys? Because this mode is exactly what I needed

**Comment by itsarian** [comment]
any updates?

**Comment by gliscowo** [comment]
Indeed, I've just released [0.4.0 for 1.21](https://modrinth.com/mod/deathlog/version/0.4.0+1.21). Please be aware that due to the changes necessitated by the game, DeathLog now stores an individual database for each world and the format has changed - your old databases will no longer work

Thanks everyone for being patient!

**Comment by itsarian** [comment]
hmm, any idea on how to somehow convert our old databases over to the new one?
